### ISSUE TITLE
Traverse shadowRoots when binding links

### ISSUE THREAD

**Issue by mkay581** [mkay581/router-component#10]
When hitting a route, the current implementation binds relative <a> links to prevent full page reloads, but does not do this for links that are nested within shadowRoot of route elements.

Unfortunately, there is currently no way to easily traverse all shadow roots within a route element. But there are [discussions about adding this functionality to the spec](https://github.com/whatwg/dom/issues/665). In the meantime it may make sense for us to just do this manually.

**Comment by ernsheong** [comment]
pwa-helpers does it by listening to clicks in the `body`

https://github.com/Polymer/pwa-helpers/blob/master/src/router.ts#L47

Does this circumvent the need to traverse and bind?

**Comment by mkay581** [comment]
Oh sure! I didn't realize that clicks still register on the `<body>` element when they are nested inside of shadow DOM.  I see that it also even works if the propagation is stopped beforehand.

I don't believe this works for any other elements, which kind of surprises me. Do you know if this is clearly defined in the spec somewhere? I just wanna make sure that all browsers will adhere to this behavior.

**Comment by mkay581** [comment]
After looking at this a little more closely, it looks like, anytime any `<a>` is clicked, they are looping through all of the elements in the compose path to find the clicked `<a>` element, which isn't very good for performance :disappointed: . Also, looks like composed paths don't work for clicks inside of closed shadow DOMs. Their method is a great temporary solution, but being able to only set listeners where necessary may be the best approach going forward.

**Comment by mkay581** [comment]
We can possibly use the [`query-selector-shadow-dom` package](https://github.com/Georgegriff/query-selector-shadow-dom) that can pierce Shadow DOM roots without knowing the path through nested shadow roots.

**Comment by mkay581** [comment]
The original issue has been fixed in 0393f440a77e8fa56f9703d91ddf30a500db943d and has since been available in version 0.4.0 of the package. Closing.
