### ISSUE TITLE
Add ES "module" entrypoint for package

### ISSUE THREAD

**Issue by shinobi5** [mkay581/router-component#15]
Any chance an ESM `module` entry point can be added to `package.json`?

Previously I used a bundler when using this component in a project but I'm now switching to using [pikapkg/web](https://github.com/pikapkg/web) to generate browser ready packages. 

Searched for it at https://www.pikapkg.com/packages/?q=router-component and found that it doesn't have a module entry point although it appears it's already an esm module.

Small update to add this?

**Comment by mkay581** [comment]
oh sure! Did you wanna open a PR? or should I?

**Comment by shinobi5** [comment]
I'm happy to do it, thanks!

**Comment by mkay581** [comment]
Released in version 0.8.0
