### ISSUE TITLE
Nested routing?

### ISSUE THREAD

**Issue by ernsheong** [mkay581/router-component#9]
Does this component allow nested routing? It looks like it assumes at most one `<router-component>` for the entire app.

Use case: I want to be able to have a nested component handle routing within the component itself. E.g. When I use a tabs component, clicking on separate tabs updates the URL and triggers different views.

**Comment by mkay581** [comment]
Ah yes, I actually have a local branch where I've started this. I plan to finish it in the next day or so. I'll let you know here once its complete.

**Comment by mkay581** [comment]
Hey @ernsheong just added this and published in version 0.3.0 of the package. I've also added [a nested tab example](https://github.com/mkay581/router-component/blob/master/examples/nested-tabs/index.html) that you may reference. If you should wish to test the examples, I've provided some [instructions on running the examples in the README](https://github.com/mkay581/router-component#more-examples).

This package is in its early stages and I've been using it on a few experimental projects and its been working well, even with the new Lit Elements and Custom Web Components, which are the future of the web! So feel free to try it out and open issues if you should see any.

**Comment by ernsheong** [comment]
Hey appreciate it, looking forward to trying it out!
